
	SELECT 
	T_CARTERA_EJECUTIVA_PROYECTOS.`ID_PROYECTO`
	,T_CARTERA_EJECUTIVA_PROYECTOS.`FOLIO_PROYECTO`
	,T_CARTERA_EJECUTIVA_PROYECTOS.FEC_REGISTRO
	,CONCAT('DGTIC/DAP/IPP/17/',T_CARTERA_EJECUTIVA_PROYECTOS.FOLIO_PROYECTO) AS NOMBRE_PROYECTO
	,C_UNIDADES_RESPONSABLES.UNIDAD_RESPONSABLE
	,T_CARTERA_EJECUTIVA_PROYECTOS.FEC_LINEA_BASE_INICIO
	,T_CARTERA_EJECUTIVA_PROYECTOS.FEC_LINEA_BASE_FIN
	,T_CARTERA_EJECUTIVA_PROYECTOS.`NOMBRE_LIDER_PROYECTO`
	,T_CARTERA_EJECUTIVA_PROYECTOS.`PRESUPUESTO_ESTIMADO`
	,C_FASES_PROYECTO.FASE_PROYECTO
	,C_EDN.OBJETIVOS_SEC_EDN AS EDN
	,GROUP_CONCAT(C_FORMATOS_RECIBIDOS.NOMBRE_CORTO) AS FORMATO
	FROM T_DETALLE_FORMATO
	INNER JOIN T_CARTERA_EJECUTIVA_PROYECTOS ON T_CARTERA_EJECUTIVA_PROYECTOS.ID_PROYECTO = T_DETALLE_FORMATO.ID_PROYECTO
	INNER JOIN C_UNIDADES_RESPONSABLES ON C_UNIDADES_RESPONSABLES.ID_UR = T_CARTERA_EJECUTIVA_PROYECTOS.ID_UR
	INNER JOIN C_FORMATOS_RECIBIDOS ON C_FORMATOS_RECIBIDOS.ID_FORMATO = T_DETALLE_FORMATO.ID_FORMATO
	INNER JOIN C_FASES_PROYECTO ON C_FASES_PROYECTO.ID_FASE_PROYECTO = T_CARTERA_EJECUTIVA_PROYECTOS.ID_FASE_PROYECTO
	INNER JOIN C_EDN ON C_EDN.ID_EDN = T_CARTERA_EJECUTIVA_PROYECTOS.ID_EDN
	WHERE FEC_OFICIO_REG BETWEEN '2017-01-01' AND '2017-03-31'
	GROUP BY FOLIO_PROYECTO
	ORDER BY FOLIO_PROYECTO ASC 